spring:
  profiles:
    active: local

# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: /delicious-food-map

mybatis-plus:
  # 配置mapper扫描位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置控制台打印mybatis sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 日期时间字段格式化
    date-format: yyyy-MM-dd HH:mm:ss